# Step 1: Ensure TARGET is correctly set and echo all variables
echo "Setting up build environment"
TARGET=${{ matrix.target }}
GCC_VERSION=13.3.0

case "$TARGET" in
  "mediatek/filogic") ARCH="aarch64_cortex-a53"; EABI_SUFFIX="";;
  "mediatek/mt7622") ARCH="aarch64_cortex-a53"; EABI_SUFFIX="";;
  "qualcommax/ipq807x") ARCH="aarch64_cortex-a53"; EABI_SUFFIX="";;
  "ramips/mt7621") ARCH="mipsel_24kc"; EABI_SUFFIX="";;
  "rockchip/armv8") ARCH="aarch64_generic"; EABI_SUFFIX="";;
  "ipq40xx/chromium") ARCH="arm_cortex-a7_neon-vfpv4"; EABI_SUFFIX="_eabi";;
  "ipq40xx/mikrotik") ARCH="arm_cortex-a7_neon-vfpv4"; EABI_SUFFIX="_eabi";;
  *) echo "Unknown target $TARGET"; exit 1;;
esac

echo "Target: $TARGET"
echo "ARCH: $ARCH"
echo "EABI_SUFFIX: $EABI_SUFFIX"

# Step 2: Construct the SDK_URL
SDK_URL="https://downloads.openwrt.org/snapshots/targets/${TARGET//\//-}/openwrt-sdk-${TARGET//\//-}_gcc-${GCC_VERSION}_musl${EABI_SUFFIX}.Linux-x86_64.tar.zst"

# Debugging - Print the final constructed URL
echo "SDK URL: $SDK_URL"

# Step 3: Download the SDK
wget $SDK_URL
if [ $? -ne 0 ]; then
  echo "Error downloading SDK for $TARGET"
  exit 1
fi

# Step 4: Extract the SDK
tar -xvf openwrt-sdk-${TARGET//\//-}_gcc-${GCC_VERSION}_musl${EABI_SUFFIX}.Linux-x86_64.tar.zst

# Step 5: Set SDK directory variable
SDK_DIR=$(basename openwrt-sdk-${TARGET//\//-}_gcc-${GCC_VERSION}_musl${EABI_SUFFIX}.Linux-x86_64.tar.zst .tar.zst)
echo "SDK Directory: $SDK_DIR"
